[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_minter = "DsE7aWa6rh3P4F2Y8eDdThq4oqzpXeNAroH56wjqyyDC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/trankhacvy/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/0.all.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dump/metadata.so"
